export const Specialization= {
    GENERAL_MEDICINE: "General Medicine",
    CARDIOLOGY: "Cardiolog",
    ENDOCRINOLOGY: "Endocrinology",
    GASTROENTEROLOGY: "Gastroenterology",
    HEMATOLOGY: 'Hematology',
    INFECTIOUS_DISEASE: 'Infectious Disease',
    NEPHROLOGY: 'Nephrology',
    NEUROLOGY: 'Neurology',
    ONCOLOGY: 'Oncology',
    OPHTHALMOLOGY: 'Ophthalmology',
    ORTHOPEDICS: 'Orthopedics',
    OTOLARYNGOLOGY: 'Otolaryngology',
    PEDIATRICS: 'Pediatrics',
    PSYCHIATRY: 'Psychiatry',
    PULMONOLOGY: 'Pulmonology',
    RADIOLOGY: 'Radiology',
    UROLOGY: 'Urology',
    OBSTETRICS_AND_GYNECOLOGY: 'Obstetrics and Gynecology',
    SURGERY: 'Surgery',
    ANESTHESIOLOGY: 'Anesthesiology',
    PATHOLOGY: 'Pathology',
    RHEUMATOLOGY: 'Rheumatology',
    PHYSICAL_MEDICINE_AND_REHABILITATION: 'Physical Medicine and Rehabilitation',
    ALLERGY_AND_IMMUNOLOGY: 'Allergy and Immunology',
    GERIATRICS: 'Geriatrics',
    CRITICAL_CARE_MEDICINE: 'Critical Care Medicine',
    ENDOCRINE_SURGERY: 'Endocrine Surgery',
    PAIN_MANAGEMENT: 'Pain Management',
    GENETICS: 'Genetics'
}


